version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:

### Clipsal C-Gate Server #########################################
    cgate:
      build:
        context: ./cgate
      ports:
        - "20023:20023"
        - "20025:20025"
        - "20026:20026"
        - "20123:20123"
      volumes:
        - ./cgate/config/C-GateConfig.txt:/cgate/config/C-GateConfig.txt
        - ./cgate/config/access.txt:/cgate/config/access.txt
        - ./cgate/config/NET1.xml:/cgate/tag/NET1.xml
      networks:
        - backend
      restart: unless-stopped

### NGINX Server #########################################
    nginx:
      build: ./nginx
      volumes:
        - ./nginx/ssl:/etc/nginx/ssl
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/start-nginx.sh:/nginx/start-nginx.sh
      ports:
        - "8888:8888" # http
        - "443:443" # https
      depends_on:
        - python
        - vue
      networks:
        - frontend
        - backend
      restart: unless-stopped

### Web ##############################################

    python:
      build: ./python
      command: uvicorn main.main:app --host 0.0.0.0 --port 8000 --reload
      #command: gunicorn main.main:app --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker
      volumes:
        - ../code/fastapi:/app:cached
      working_dir: /app
      ports:
        - "8000:8000"
      depends_on:
        - redis
      networks:
        - backend
      restart: unless-stopped

### Vue ##############################################

    vue:
      build: ../code/vue/
      command: npm run serve #change this to 'tail -f /dev/null' is to start the container to run the cli
      volumes:
        - ../code/vue/:/vue:cached
        - /vue/app/node_modules
      working_dir: /vue/app
      ports:
        - "4000:4000"
        - "4001:8000" # vue-cli ui type: vue ui --headless --host 0.0.0.0
      networks:
        - frontend
        - backend
      restart: unless-stopped

### Redis DB ################################################

    redis:
      build: ./redis
      ports:
        - "6379:6379"
      volumes:
        - ../data/redis:/data
      networks:
        - backend
      restart: unless-stopped

