version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:

### Clipsal C-Gate Server #########################################
    cgate:
      build:
        context: ./cgate
      ports:
        - "20023:20023"
        - "20025:20025"
        - "20026:20026"
        - "20123:20123"
      volumes:
        - ./cgate/config/C-GateConfig.txt:/cgate/config/C-GateConfig.txt
        - ./cgate/config/access.txt:/cgate/config/access.txt
        - ./cgate/config/NET1.xml:/cgate/tag/NET1.xml
      networks:
        - backend

### NGINX Server #########################################
    nginx:
      build:
        context: ./nginx
      volumes:
        - ../code/php:/code:cached
        - ../code/static:/static:cached
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/ssl:/etc/nginx/ssl
      ports:
        - "80:80" # http
        - "443:443" # https
        - "9090:9090" # php
      depends_on:
        - python
        #- vue
      networks:
        - frontend
        - backend

### Python ##############################################

    python:
      build: ./python
      volumes:
        - ../code/fastapi:/app:cached
      working_dir: /app
      ports:
        - "8888:8888"
      depends_on:
        - redis
      networks:
        - backend

### Vue ##############################################
#
#    vue:
#      build: ../code/vue
#      volumes:
#        - ../code/vue:/app:cached
#        - /app/node_modules
#      working_dir: /app
#      ports:
#        - "4000:4000"
#      networks:
#        - frontend
#        - backend

### Redis DB ################################################

    redis:
      build: ./redis
      ports:
        - "6379:6379"
      volumes:
        - ../data/redis:/data
      networks:
        - backend

### PHP ##############################################
  
    php:
      build:
        context: ./php-fpm
      ports:
        - "9000:9000"
        - "5000:5000" # websockets
      volumes:
        - ./php-fpm/php73.ini:/usr/local/etc/php/php.ini
        - ./php-fpm/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        - ../code/php:/code:cached
      networks:
        - backend

