
card0001:
  card: 'dimmer_1'
  label: 'Master Bedroom Lights'
  icon: 'mdi-lightbulb-outline'
  devices:
    - 'cgate.master_bedroom_lights' # listener is the first one in the list
  command_params:
    ramp_time: 4
  fave_1: 15
  fave_2: 40
  groups:
    - 'Lights'
  zones:
    - 'All Upstairs'
    - 'Master Bedroom'

card0002:
  card: 'dimmer_1'
  label: 'Nia''s Bedroom Lights'
  icon: 'mdi-lightbulb-outline'
  devices:
    - 'cgate.nias_bedroom_lights'
  fave_1: 15
  fave_2: 40
  groups:
    - 'Lights'
  zones:
    - 'All Upstairs'
    - 'Nia''s Bedroom'

card0003:
  card: 'dimmer_1'
  label: 'Study Lights'
  icon: 'mdi-lightbulb-outline'  
  devices:
    - 'cgate.study_lights'
  fave_1: 15
  fave_2: 40
  groups:
    - 'Lights'
  zones:
    - 'All Upstairs'
    - 'Study'

wgt5003:
  card: 'dimmer_1'
  label: 'Study Lights 2'
  icon: 'mdi-lightbulb-outline'
  devices:
    - 'cgate.study_lights'
  fave_1: 15
  fave_2: 40
  groups:
    - 'Lights'
  zones:
    - 'All Upstairs'
    - 'Study'

card0200:
  card: 'dimmer_rgb_1'
  label: 'Master LED Strip'
  icon: 'mdi-led-strip-variant'
  devices:
    - 'hue.master_led_strip'
  fave_1: 20
  fave_2: 50
  groups:
    - 'Lights'
    - 'Hue'
  zones:
    - 'All Upstairs'
    - 'Master Bedroom'

card0201:
  card: 'dimmer_rgb_1'
  label: 'Stairs LED Strip'
  icon: 'mdi-led-strip-variant'
  devices:
    - 'hue.stairs_led_strip'
  fave_1: 20
  fave_2: 50
  groups:
    - 'Lights'
    - 'Hue'
  zones:
    - 'All Upstairs'

card0102:
  card: 'switch_1'
  label: 'Ensuite Lights'
  icon: 'mdi-lightbulb-outline'
  devices:
    - 'cgate.ensuite_lights'
  groups:
    - 'Lights'
  zones:
    - 'All Upstairs'
    - 'Master Bedroom'

card0103:
  card: 'switch_1'
  label: 'Ensuite Fan'
  icon: 'mdi-fan'
  devices:
    - 'cgate.ensuite_fan'
  groups:
    - 'Devices'
  zones:
    - 'All Upstairs'
    - 'Master Bedroom'

card0104:
  card: 'switch_1'
  label: 'Ensuite Ceiling Heat'
  icon: 'mdi-fire'
  devices:
    - 'cgate.ensuite_ceiling_heat'
  groups:
    - 'Devices'
  zones:
    - 'All Upstairs'
    - 'Master Bedroom'

card0004:
  card: 'dimmer_1'
  label: 'Dining Lights'
  icon: 'mdi-lightbulb-outline'
  devices:
    - 'cgate.dining_lights'
  fave_1: 15
  fave_2: 40
  groups:
    - 'Lights'
  zones:
    - 'All Downstairs'
    - 'Living Area'

card0005:
  card: 'dimmer_1'
  label: 'Lounge Lights'
  icon: 'mdi-lightbulb-outline'
  devices:
    - 'cgate.lounge_lights'
  fave_1: 15
  fave_2: 40
  groups:
    - 'Lights'
  zones:
    - 'All Downstairs'
    - 'Living Area'

card0006:
  card: 'dimmer_1'
  label: 'Kitchen Lights'
  icon: 'mdi-lightbulb-outline'
  devices:
    - 'cgate.kitchen_lights'
  fave_1: 15
  fave_2: 40
  groups:
    - 'Lights'
  zones:
    - 'All Downstairs'
    - 'Living Area'

card0007:
  card: 'dimmer_1'
  label: 'Entrance Lights'
  icon: 'mdi-lightbulb-outline'
  devices:
    - 'cgate.entrance_lights'
  fave_1: 15
  fave_2: 40
  groups:
    - 'Lights'
  zones:
    - 'All Downstairs'
    - 'Entrance'

card0008:
  card: 'dimmer_1'
  label: 'Dim Downstairs'
  icon: 'mdi-lightbulb-group-outline'
  devices:
    - 'cgate.kitchen_lights'
    - 'cgate.dining_lights'
    - 'cgate.lounge_lights'
  fave_1: 20
  fave_2: 50
  groups:
    - 'Lights'
    - 'Scenes'
  zones:
    - 'All Downstairs'
    - 'Living Area'

card0009:
  card: 'switch_1'
  label: 'Bathroom Lights'
  icon: 'mdi-lightbulb-outline'
  devices:
    - 'cgate.bathroom_lights'
  groups:
    - 'Lights'
  zones:
    - 'All Downstairs'
    - 'Bathroom'

card0010:
  card: 'switch_1'
  label: 'Bathroom Fan'
  icon: 'mdi-fan'
  devices:
    - 'cgate.bathroom_fan'
  groups:
    - 'Devices'
  zones:
    - 'All Downstairs'
    - 'Bathroom'

card0011:
  card: 'switch_1'
  label: 'Bathroom Ceiling Heat'
  icon: 'mdi-fire'
  devices:
    - 'cgate.bathroom_ceiling_heat'
  groups:
    - 'Devices'
  zones:
    - 'All Downstairs'
    - 'Bathroom'

card0012:
  card: 'switch_1'
  label: 'Front Door Light'
  icon: 'mdi-lightbulb-outline'
  devices:
    - 'cgate.front_door_light'
  groups:
    - 'Lights'
  zones:
    - 'All Downstairs'
    - 'Entrance'

card0101:
  card: 'switch_1'
  label: 'Master LED Strip'
  icon: 'mdi-power-plug-outline'
  devices:
    - 'cgate.master_led_strip'
  groups:
    - 'Isolators'

card0105:
  card: 'switch_1'
  label: 'Stairs LED Strip'
  icon: 'mdi-power-plug-outline'
  devices:
    - 'cgate.stairs_led_strip'
  groups:
    - 'Isolators'
