
set_device_val:
  description: 'set device val'
  actions:
    - method: 'core@SetDeviceVal'
      params: null

cmd0001:
  description: 'dim master lights'
  actions:
    - method: 'cgate@SetBrightness'
      params:
        device_id: 'NET1_254_56_0'
        set_val: null
        ramp_time: 4

