

cgate:
  master_bedroom_lights:
    address: 'NET1_254_56_0'

  nias_bedroom_lights:
    address: 'NET1_254_56_3'

  study_lights:
    address: 'NET1_254_56_5'

  ensuite_lights:
    address: 'NET1_254_56_2'

  master_led_strip:
    address: 'NET1_254_56_17'

  ensuite_fan:
    address: 'NET1_254_56_1'

  ensuite_ceiling_heat:
    address: 'NET1_254_56_11'

  stairs_led_strip:
    address: 'NET1_254_56_6'

  dining_lights:
    address: 'NET1_254_56_8'

  lounge_lights:
    address: 'NET1_254_56_9'

  kitchen_lights:
    address: 'NET1_254_56_15'

  entrance_lights:
    address: 'NET1_254_56_16'

  bathroom_lights:
    address: 'NET1_254_56_12'

  bathroom_fan:
    address: 'NET1_254_56_18'

  bathroom_ceiling_heat:
    address: 'NET1_254_56_21'

  front_door_light:
    address: 'NET1_254_56_24'

  pergola_light:
    address: 'NET1_254_56_19'

  bedroom_led_strip__rgb__brightness:
    address: 'NET1_254_56_25'

  bedroom_led_strip__rgb__red:
    address: 'NET1_254_56_26'

  bedroom_led_strip__rgb__green:
    address: 'NET1_254_56_27'

  bedroom_led_strip__rgb__blue:
    address: 'NET1_254_56_28'

hue:
  stairs_led_strip:
    address: '2'
    model: 'LST002'

  master_led_strip:
    address: '3'
    model: 'LST002'


