
zones:
  - label: 'All Upstairs'
    icon: 'mdi-stairs-up'

  - label: 'Master Bedroom'
    icon: 'mdi-bed-king-outline'

  - label: 'Nia''s Bedroom'
    icon: 'mdi-bed-outline'

  - label: 'Study'
    icon: 'mdi-desk'

  - label: 'All Downstairs'
    icon: 'mdi-stairs-down'

  - label: 'Living Area'
    icon: 'mdi-television-classic'

  - label: 'Entrance'
    icon: 'mdi-door'

  - label: 'Bathroom'
    icon: 'mdi-hot-tub'

groups:
  - label: 'Lights'
    icon: 'mdi-power-plug-outline'

  - label: 'Hue'
    icon: 'mdi-led-strip-variant'

  - label: 'Devices'
    icon: 'mdi-fan'

  - label: 'Scenes'
    icon:  'mdi-lightbulb-group-outline'

  - label: 'Isolators'
    icon: 'mdi-power-plug-outline'