
### Crave Core  #########################################
core:
  active: true
  module_name: 'core'


### Clipsal C-Gate for C-Bus ##################################
cgate:
  active: true
  module_name: 'cgate'
  host: 'cgate' # cgate host name inside docker or the IP address
  change_port: 20025 # cgate load change port
  command_port: 20023 # cgate command port
  project: 'NET1' # cgate project name as set up in cgate config xml file
  network: '254' # the number of your network for this interface
  app: '56' # the app for the lighting network - will expand to other apps in future
  event_timeout: .001 #seconds
  command_timeout: 1
  ramp_time: 4


### Philips Hue #########################################
hue:
  active: true
  module_name: 'hue'
  bridge_url: 'http://192.168.2.223/api/nA54rAAXRvvNMoSuOPcxE9y7gzhH9qVzdo5Of2M0/' # full url of the hue bridge
  poll_time: 1 #seconds


