
wgt0100:
  label: 'Downstairs Lights'
  widget: 'dimmer_1'
  devices:
    - 'cgate.kitchen_lights' # listener is the first one
    - 'cgate.dining_lights'
    - 'cgate.lounge_lights'
  command_params:
    ramp_time: 4
  fave_1: 15
  fave_2: 40
  groups:
    - Lights
    - Upstairs


wgt0001:
  widget: 'dimmer_1'
  name: 'Master Bedroom Lights'
  listener_interface: 'cgate'
  listener_device_id: 'NET1_254_56_0'
  listener_state_key: 'level'
  ui_style: ''
  fave_percentage_1: 15
  fave_percentage_2: 40
  command: 'cmd0002'
  groups:
    - 'Lights'
    - 'Upstairs'

wgt0002:
  widget: 'dimmer_1'
  name: 'Nia''s Bedroom Lights'
  listener_interface: 'cgate'
  listener_device_id: 'NET1_254_56_3'
  listener_state_key: 'level'
  ui_style: ''
  fave_percentage_1: 15
  fave_percentage_2: 40
  command: 'cmd0002'
  groups:
    - 'Lights'
    - 'Upstairs'

wgt0003:
  widget: 'dimmer_1'
  name: 'Study Lights'
  listener_interface: 'cgate'
  listener_device_id: 'NET1_254_56_5'
  listener_state_key: 'level'
  ui_style: ''
  fave_percentage_1: 15
  fave_percentage_2: 40
  command: 'cmd0003'
  groups:
    - 'Lights'

wgt0102':
  widget: 'switch_1'
  name: 'Ensuite Lights'
  listener_interface: 'cgate'
  listener_device_id: 'NET1_254_56_2'
  listener_state_key: 'level'
  ui_style: ''
  command: 'cmd0022'
  groups:
    - 'Lights'
    - 'Upstairs'

wgt0101:
  widget: 'switch_1'
  name: 'Master LED Strip'
  listener_interface: 'cgate'
  listener_device_id: 'NET1_254_56_17'
  listener_state_key: 'level'
  ui_style: ''
  command: 'cmd0015'
  groups:
    - 'Isolators'

wgt0103:
  widget: 'switch_1'
  name: 'Ensuite Fan'
  listener_interface: 'cgate'
  listener_device_id: 'NET1_254_56_1'
  listener_state_key: 'level'
  ui_style: ''
  command: 'cmd0009'
  groups:
    - 'Devices'
    - 'Upstairs'

wgt0104:
  widget: 'switch_1'
  name: 'Ensuite Ceiling Heat'
  listener_interface: 'cgate'
  listener_device_id: 'NET1_254_56_11'
  listener_state_key: 'level'
  ui_style: ''
  command: 'cmd0011'
  groups:
    - 'Devices'
    - 'Upstairs'

wgt0105:
  widget: 'switch_1'
  name: 'Stairs LED Strip'
  listener_interface: 'cgate'
  listener_device_id: 'NET1_254_56_6'
  listener_state_key: 'level'
  ui_style: ''
  command: 'cmd0023'
  groups:
    - 'Isolators'

wgt0004:
  widget: 'dimmer_1'
  name: 'Dining Lights'
  listener_interface: 'cgate'
  listener_device_id: 'NET1_254_56_8'
  listener_state_key: 'level'
  ui_style: ''
  fave_percentage_1: 15
  fave_percentage_2: 40
  command: 'cmd0004'
  groups:
    - 'Lights'
    - 'Downstairs'

wgt0005:
  widget: 'dimmer_1'
  name: 'Lounge Lights'
  listener_interface: 'cgate'
  listener_device_id: 'NET1_254_56_9'
  listener_state_key: 'level'
  ui_style: ''
  fave_percentage_1: 15
  fave_percentage_2: 40
  command: 'cmd0005'
  groups:
    - 'Lights'
    - 'Downstairs'

wgt0006:
  widget: 'dimmer_1'
  name: 'Kitchen Lights'
  listener_interface: 'cgate'
  listener_device_id: 'NET1_254_56_15'
  listener_state_key: 'level'
  ui_style: ''
  fave_percentage_1: 15
  fave_percentage_2: 40
  command: 'cmd0006'
  groups:
    - 'Lights'
    - 'Downstairs'

wgt0007:
  widget: 'dimmer_1'
  name: 'Entrance Lights'
  listener_interface: 'cgate'
  listener_device_id: 'NET1_254_56_16'
  listener_state_key: 'level'
  ui_style: ''
  fave_percentage_1: 15
  fave_percentage_2: 40
  command: 'cmd0007'
  groups:
    - 'Lights'
    - 'Downstairs'

wgt0008:
  widget: 'dimmer_1'
  name: 'Dim Downstairs'
  listener_interface: 'cgate'
  listener_device_id: 'NET1_254_56_8'
  listener_state_key: 'level'
  ui_style: ''
  fave_percentage_1: 20
  fave_percentage_2: 50
  command: 'cmd0008'
  groups:
    - 'Lights'
    - 'Scenes'
    - 'Downstairs'

wgt0009:
  widget: 'switch_1'
  name: 'Bathroom Lights'
  listener_interface: 'cgate'
  listener_device_id: 'NET1_254_56_12'
  listener_state_key: 'level'
  ui_style: ''
  command: 'cmd0012'
  groups:
    - 'Lights'
    - 'Downstairs'

wgt0010:
  widget: 'switch_1'
  name: 'Bathroom Fan'
  listener_interface: 'cgate'
  listener_device_id: 'NET1_254_56_18'
  listener_state_key: 'level'
  ui_style: ''
  command: 'cmd0016'
  groups:
    - 'Devices'
    - 'Downstairs'

wgt0011:
  widget: 'switch_1'
  name: 'Bathroom Ceiling Heat'
  listener_interface: 'cgate'
  listener_device_id: 'NET1_254_56_21'
  listener_state_key: 'level'
  ui_style: ''
  command: 'cmd0017'
  groups:
    - 'Devices'
    - 'Downstairs'

wgt0012:
  widget: 'switch_1'
  name: 'Front Door Light'
  listener_interface: 'cgate'
  listener_device_id: 'NET1_254_56_24'
  listener_state_key: 'level'
  ui_style: ''
  command: 'cmd0020'
  groups:
    - 'Lights'
    - 'Downstairs'

wgt0013:
  widget: 'switch_1'
  name: 'Stairs LED Strip'
  listener_interface: 'hue'
  listener_device_id: '2'
  listener_state_key: 'level'
  ui_style: ''
  command: 'c23'
  groups:
    - 'Lights'
    - 'Hue'

wgt0014:
  widget: 'dimmer_1'
  name: 'Stairs LED Strip'
  listener_interface: 'hue'
  listener_device_id: '2'
  listener_state_key: 'level'
  ui_style: ''
  fave_percentage_1: 20
  fave_percentage_2: 50
  command: 'c24'
  groups:
    - 'Lights'
    - 'Hue'

wgt0015:
  widget: 'switch_1'
  name: 'Bedroom LED Strip'
  listener_interface: 'hue'
  listener_device_id: '3'
  listener_state_key: 'level'
  ui_style: ''
  command: 'c25'
  groups:
    - 'Lights'
    - 'Hue'

wgt0016:
  widget: 'dimmer_1'
  name: 'Bedroom LED Strip'
  listener_interface: 'hue'
  listener_device_id: '3'
  listener_state_key: 'level'
  ui_style: ''
  fave_percentage_1: 20
  fave_percentage_2: 50
  command: 'c26'
  groups:
    - 'Lights'
    - 'Hue'


