
wgt0100:
  label: 'Downstairs Lights'
  widget: 'dimmer_1'
  devices:
    - 'cgate.kitchen_lights' # listener is the first one
    - 'cgate.dining_lights'
    - 'cgate.lounge_lights'
  command_params:
    ramp_time: 4
  fave_1: 15
  fave_2: 40
  groups:
    - Lights
    - Scenes

wgt0101:
  label: 'Lounge Lights'
  widget: 'dimmer_1'
  devices:
    - 'cgate.lounge_lights'
  command_params:
    ramp_time: 4
  fave_1: 15
  fave_2: 40
  groups:
    - Lights
    - Downstairs

wgt0101:
  label: 'Dining Lights'
  widget: 'dimmer_1'
  devices:
    - 'cgate.dining_lights'
  command_params:
    ramp_time: 4
  fave_1: 15
  fave_2: 40
  groups:
    - Lights
    - Downstairs

